[workspace]
resolver = "3"
members = ["crates/media", "crates/app", "crates/telemetry"]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "GPL-3.0-or-later"
publish = false

[workspace.dependencies]
ffmpeg-next = { version = "9.0", default-features = false, features = ["codec", "format", "software-resampling", "software-scaling", "static"] }
crossbeam-channel = "0.5"
cpal = "0.18"
ringbuf = "0.5"
thiserror = "2"
log = "0.4"
chrono = { version = "0.4.45", default-features = false, features = ["std"] }
geographiclib-rs = "0.2.7"
anyhow = "1"
